### ISSUE TITLE
avoid full entry XML transfer when listing entries

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#101]
Now this is necessary for subbing and flagging. The latter can be solved by an extra column for flags, no idea about the former though.

**Comment by mjakubicek** [comment]
Miloš will fix it for flagging, Michal for subbing.

**Comment by iztokkosem** [comment]
I am not sure whether this has been fixed or successfully migrated to python when rewriting from Javascript, as we are still encountering long upload times.

**Comment by rambousek** [comment]
save flag in separate row

**Comment by mjakubicek** [comment]
column ;-)

**Comment by iztokkosem** [comment]
I think this has been address by uploading first X entries in the database in large databases?
