### ISSUE TITLE
viewing problem (css) in Editor on smaller screens

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#104]
When shrinking Lexonomy on smaller screens, the icons of the Editor at the top overlap. This should be solved with CSS, as we discussed at the hackathon. Screenshot attached.

![Lexonomy-narrowscreen](https://user-images.githubusercontent.com/46104191/56574668-1b729400-65c4-11e9-817d-3131f966a0ea.png)

**Comment by michmech** [comment]
Two options:

1. When the screen becomes narrow, make the buttons flow into a second line, or
2. When the screen becomes narrow, shrink the buttons so only the icon is visible and the caption disappears.

**Comment by mjakubicek** [comment]
Solvable with a bit more responsive design

**Comment by rambousek** [comment]
> 1. When the screen becomes narrow, make the buttons flow into a second line, or

I vote for 1 :)

**Comment by iztokkosem** [comment]
Looking at the buttons, I would probably leave Edit (then Save and Cancel) visible, as these are mainly used, and shrink all the other buttons in a hamburger (like with responsive design on mobile devices).

**Comment by rambousek** [comment]
New editor UI will be responsive.
