### ISSUE TITLE
Using middleware

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#105]
To decrease the "triangular code" and remove some indentation, we could use express.js's middleware. It also gives you much more [DRY code](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and all of that...

I am providing an example of using it for authentication (diff in meld, faster than pull/merge request)

![diff](https://i.imgur.com/w0Kmp6C.png)

**Comment by mjakubicek** [comment]
Yes, please do it! :+1:

**Comment by gareins** [comment]
Now, this example here is a bit more problematic, as middleware is not really loved :)
Cons: 
* we are using more middleware and this is bad, although citation needed please, I really want to see how things can go wrong...

Pros: 
* 36 * 2 lines removed (if we use `req.db` instead of `db`)
* unified 404 redirect, not 36 copies of the same code.
* Easier to add additional checks on `db` object, since the file could be corrupted. Currently this would have to be done 36 times.

![diff2](https://i.imgur.com/vck0yXB.png)

Also, some lines here are missing for the readonly flag, but that is easy to add...

**Comment by mjakubicek** [comment]
no longer relevant since we switched to Python
