### ISSUE TITLE
Importing 85MB dictionary

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#11]
I have tried to import a dictionary, but the app starts posting a huge number of sqlite errors:

` Error: SQLITE_BUSY: database is locked errno: 5, code: 'SQLITE_BUSY' `

By following the code and running the profiler, I see that pretty much all the time the code is computing import function from ops.js, running regex matching and copying data using memcpy. The process does not end in a couple of hours. How should I handle this?

I have also uncommented those console.log calls (CREATED, UPDATED, going to create) and they get printed from the beginning, but then everything stops, however CPU is still on 100%

EDIT: now more are being printed, I'll see if this is finished by the morning.

**Comment by mjakubicek** [comment]
This should be fixed now.
