### ISSUE TITLE
Add 'community files' for developers

### ISSUE THREAD

**Issue by iiegn** [elexis-eu/lexonomy#112]
The project should provide (at least) the following files/templates/descriptions inside README:
- [X] `CONTRIBUTING.md` guidelines
- [X] `issue_template.md` 
- [x] ?~~`pull_request_template.md`~~
- [X] ?Code of conduct
- [X] Code style guidelines

**Comment by iiegn** [comment]
The `CONTRIBUTING.md` guidelines should specify the legal status of contributions.

Some inspiration might come (ironically) from gitlab (not github). [They use Version 1.1](https://gitlab.com/gitlab-org/dco/blob/master/README.md) of a so-called [Developer Certificate of Origin](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin). Alternatively, a [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement) could be used. Other alternatives certainly exists, too...

I think, the details should come from @mjakubicek and @iztokkosem and @simonkrek

**Comment by mjakubicek** [comment]
I understand why you would prefer (me too) a DCO but we cannot use it. None of the developers-employees has the right to sign it, so we need to go through a corporate and individual CLA. I will forward an ongoing discussion on that topic.

**Comment by iiegn** [comment]
i moved this issue [to the D4.1 milestone](../milestone/2): the DCO/CLA-thing should also be done by then, to make sure (also new) people know what to expect...

**Comment by iiegn** [comment]
There exists now 
* a [`Contributing to Lexonomy` document](https://github.com/elexis-eu/lexonomy/blob/fix-112/CONTRIBUTING.md), which addresses these points:
  - Question or Problem?
  - Issues and Bugs
  - Feature Requests
  - Submission Guidelines
  - Coding Rules
  - Commit Message Guidelines
  - Signing the CLA
  - Code of Conduct (links to CODE_OF_CONDUCT.md)
* [templates for bug reports and feature requests](https://github.com/elexis-eu/lexonomy/commit/27d885fc88e3f5727582b4868e82e322664d14a9)

@mjakubicek for signing the CLA, we are missing two links/documents, and a description of the procedure...

**Comment by iiegn** [comment]
Moved the missing 'Signing the CLA' bit to #161. Closing this issue.
