### ISSUE TITLE
Local installation not working

### ISSUE THREAD

**Issue by jan-niestadt** [elexis-eu/lexonomy#133]
With the latest version (either beta or master), I can't get Lexonomy to run locally anymore. Tried a fresh clone (on Linux Mint 18.3, based on Ubuntu 16.04), followed the instructions under [Inside a user environment](https://github.com/elexis-eu/lexonomy/blob/master/INSTALL.md#inside-a-user-environment), but I get the following error:

```
$ python3 lexonomy.py
Traceback (most recent call last):
  File "lexonomy.py", line 175, in <module>
    import paste
ImportError: No module named 'paste'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lexonomy.py", line 177, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```

**Comment by iiegn** [comment]
i understand, this won't solve the problem - but, at least, the docker version still works (this means, comparing the two environments, the one described in INSTALL.md and the automatically built one should help disentangle the issue). 
i was also thinking that having an auto-build for the 'user environment' use-case should be *a thing*.

i will self-assign the ticket and take care of these things (during the upcoming hackathon)
- [ ] update INSTALL.md (or whatever needs updating) 
- [ ] set-up minimal CI for 'user environment' use-case (i.e. bypass docker)

**Comment by mjakubicek** [comment]
The problem is that your version of Python is throwing NameError instead of ModuleNotFoundError. That is weird if it is indeed Python 3. If you replace ModuleNotFoundError with NameError, it will probably work I guess, but it is still weird. Can you post python3 --version?
Btw, I'm now in Leiden so you can drop by if you want.

**Comment by jan-niestadt** [comment]
Okay, thanks. My Python version is 3.5.2, and it seems [ModuleNotFoundError](https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError) is available starting from 3.6. I'll see if I can upgrade easily.

**Comment by jan-niestadt** [comment]
Installed 3.6, and `python3.6 lexonomy.py` seems to work, but when I load `http://localhost:8000/` in the browser, it says `400 Bad Request`. Here's the output from `lexonomy.py`:
```
Bottle v0.13-dev server starting up (using WSGIRefServer())...
Listening on http://localhost:8000/
Hit Ctrl-C to quit.

127.0.0.1 - - [12/Jun/2019 09:29:00] "GET / HTTP/1.1" 400 303
```
Maybe we can have a look this afternoon. Alternatively I'll look into Docker.

**Comment by jan-niestadt** [comment]
On my Chromebook, running Xubuntu 16.04, I get a different error when running `lexonomy.py`:
```
$ python3.6 lexonomy.py 
Traceback (most recent call last):
  File "lexonomy.py", line 4, in <module>
    import os, sys, json, sqlite3, functools, ops
  File "/home/jan/projects/tmp/lexonomy/website/ops.py", line 5, in <module>
    siteconfig = json.load(open(os.environ.get("LEXONOMY_SITECONFIG", "siteconfig.json")))
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1301: ordinal not in range(128)
```

**Comment by gareins** [comment]
first, check if LEXONOMY_SITECONFIG is defined as environment variable 

```$ [[ -v LEXONOMY_SITECONFIG ]]; echo $?```

Let's say its not defined (there is 1 in stdout). Next, check if "./siteconfig.json" is proper ascii file:

```$ file ./siteconfig.json```

If it says it is utf-8, then you could change that line to force utf-8 decode:

```
> configfile = os.environ.get("LEXONOMY_SITECONFIG", "siteconfig.json")
> json.loads(open(configfile, 'rb').read().decode('utf8'))
```

Although this should be the default by my pythonic standards, but here you get a strange ascii decode error, so try this.

**Comment by iiegn** [comment]
something is strange... try this
```bash
python3.6 -c "import sys; import os; import platform; print(sys.getfilesystemencoding()); print(sys.platform); pyioenc = os.environ['PYTHONIOENCODING'] if 'PYTHONIOENCODING' in os.environ else 'undefined'; print(pyioenc); print(platform.python_version());"
echo "LANG:"$LANG "LC_ALL:"$LC_ALL "LC_CTYPE:"$LC_CTYPE
```
...which should give something like (but the details depend on your system):
> utf-8
> linux
> undefined
> 3.6.8
> LANG:en_US.UTF-8 LC_ALL: LC_CTYPE:

and then try this:
```bash
echo "héhé"|python3.6 -c 'import sys; sys.stdout.write(sys.stdin.read())'|cat
echo "héhé"|LANG= PYTHONIOENCODING=utf-8:surrogateescape python3.6 -c 'import sys; sys.stdout.write(sys.stdin.read())'|cat
```

**Comment by jan-niestadt** [comment]
Output of the first two commands:
```
ascii
linux
undefined
3.6.8
LANG: LC_ALL: LC_CTYPE:
```

The second command doesn't copy/paste right to the terminal, probably because the default encoding seems to be ascii instead of utf-8. Probably a quirk of Xubuntu.

**Comment by jan-niestadt** [comment]
By the way @gareins, forcing utf8 fixed it. Mint is working again as well; not sure, but it seems I messed something up there before.

**Comment by iiegn** [comment]
ok, we know it's utf-8: insofar, it seems reasonable to explicitly state that it's utf-8 (because the default obviously depends on the system setting...).
still, you should do something like:
```bash
sudo dpkg-reconfigure locales
```
and set a utf-8 default locale (if you want to be as language agnostic as possible you can look for C.UTF-8. however, the availability might depend on a package and/or you have to set this _manually_ in `/etc/default/locale`).

**Comment by gareins** [comment]
My "solution" is far from perfect, because it means you have to be aware of the encoding every time you open any text file - if there are none, then fine. There are better ways however, like doing it system-wise, like @iiegn, but that is manual work. If we want it as part of the code, you could do [this](https://stackoverflow.com/a/17628350), but this has other bad side effects.

I vote for @iiegn 's solution with just a section in INSTALLATION.md and then it's the administrator's problem.

**Comment by jan-niestadt** [comment]
Unless there's a pressing reason to support other encodings, I would opt for always explicitly reading text files as UTF-8. It's a simple approach that works on any system, no matter how it's configured.

But I guess giving very clear instructions in INSTALLATION.md is also okay.

**Comment by iiegn** [comment]
and. finally. done. (re-)opened subplots from here as new issues: #139 #140
