### ISSUE TITLE
signup email using localhost url

### ISSUE THREAD

**Issue by attogram** [elexis-eu/lexonomy#134]
After filling out <https://www.lexonomy.eu/signup/> the email is sent OK, but the email contents is using localhost for the address and createaccount URL:

```
Dear Lexonomy user,

Somebody (hopefully you, from the address ::1) requested to create a new Lexonomy account. Please follow the link below to create your account:

http://localhost:8080/createaccount/blahblah....

```

**Comment by teoric** [comment]
i.e., one can sign up replacing the link <http://localhost:8080/createaccount/blahblah....>  by <https://www.lexonomy.eu/createaccount/blahblah....>.  But that's not necessarily obvious.

**Comment by michmech** [comment]
Fixed. Thanks for reporting.
