### ISSUE TITLE
pulling data from Sketch Engine and dictionary in DTD

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#149]
I have established API connection with Sketch Engine in my project. Pulling works successfully, however when I try to move the data from the widget on the right to the entry, I don't get offered any places where data could be moved.

One possible reason I see for this is that I'm using DTD rather than Lexonomy framework. Or is it something else?

**Comment by iiegn** [comment]
just-to-let-you-know: 
- i have an automatically created dictionary 
- for which i linked my account and (re?)established connection
- and i could find examples

1. what wasn't entirely clear to me, how do i get the content into my entry (when using the very top SkE-icon - not the one on the level of where the content would go):
    - initially i 'lost' examples because once i had them in the right-hand pane i 'clicked away' from the view; and differently than editing something in the left/middle pane, here no messages warns about 'unsaved changes' 
    - eventually, i figured: i have to drag content over to where it belongs

2. when using the SkE-icon on the level where the content should go, i was able to add content (in a way that i also get a warning about 'unsaved content')

**Comment by iztokkosem** [comment]
Thanks for this - yes, when I work directly, it works like a charm. I cannot drag content from the right-hand widget - perhaps because in this particular dictionary I have several places where the same example tag is allowed?

**Comment by iztokkosem** [comment]
Does somebody have an answer to this? I'm still having problems.
Is there a particular combination of features that I should use to make example pulling work? Or in other words, should I avoid using things like DTD, custom Entry editor etc.?
