### ISSUE TITLE
check SkE account on linking

### ISSUE THREAD

**Issue by rambousek** [elexis-eu/lexonomy#151]
When connecting Lexonomy account to SkE account, check if same SkE account is already connected with another Lex account.

**Comment by iiegn** [comment]
speaking of linking... might it become a problem that there seemingly is only a one-one connection between SkE and lexonomy.eu - what about lexonomy.elexis.eu (or others, like beta.lexonomy.eu)?

**Comment by iztokkosem** [comment]
And to add, what about linking between local installations of Lexonomy and SkE?

**Comment by mjakubicek** [comment]
Linking between local installation of Lexonomy and SkE works
Linking between Lexonomy and anything else is not supported -- there is no other SSO provider at the moment and it is unlikely there will be one anytime soon

**Comment by iiegn** [comment]
i think, i misunderstood the linking. there seem to be two directions, and i was concerned about what is usually referred to as the one-click dictionary, i.e. `SkE -- sending data --> lexonomy`. if i unterstand this correctly, then this direction is pre-set in SkE to `lexonomy.eu` - and maybe the only thing necessary here would be to be (more) explicit about this: OCD works only with `lexonomy.eu`.

the other direction, `lexonomy <--grabbing data-- SkE` seems to be working from different lexonomy installations but (if i understood @mjakubicek correctly) is pretty much only supported for SkE.

**Comment by mjakubicek** [comment]
You did misundersand but on a different level, this is just about linking user accounts, nothing else.  OCD or push/pull is entirely unrelated.

**Comment by iiegn** [comment]
i see, yes. 

for what it's worth:
- lexonomy.elex.is [doesn't seem to be prominently linked at the moment](https://www.google.com/search?q=%22lexonomy.elex.is%22)
 - beta.lexonomy.eu announces itself as being 'special'

and if there will ever be  
- confusion about "to where can i push one-click dictionary data from SkE?"
- the need to "push data from SkE somewhere else than lexonomy.eu"

that will be go into a new issue.

sorry for the confusion, back to @rambousek

**Comment by rambousek** [comment]
meanwhile fixed in beta :)
