### ISSUE TITLE
Info on Lexonomy version

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#156]
It would be good to include somewhere on the frontend the info about the version of Lexonomy, or the date of the last update. This is particularly relevant for local installations, e.g. when reporting issues. Currently, only the developers are able to see that, I guess.

**Comment by iiegn** [comment]
Once some (sort of version) information is available for users on the front end, update 'Contributing to Lexonomy' documentation. See  #112.

**Comment by gareins** [comment]
Shouldn't this be part of some sort of "about us" page? Which does not exist currently

**Comment by iiegn** [comment]
on a site like lexonomy.eu, i would be looking in the footer of the page(s)... but something like **help** (preferred) or **about** would do as well.
**help** could then give even more information, e.g. about the google group, etc. (similar to what i've put here: 8999f833 in `CONTRIBUTING.md`)

**Comment by iztokkosem** [comment]
We closed this issue without any explanation or final decision - I would still want a place on the version of Lexonomy, as is the practice with any tool. If you have it for beta.lexonomy.eu, why not for the others.

**Comment by rambousek** [comment]
Version is displayed both on lexonomy,eu and beta.lexonomy.eu, and it's build date plus sequence number plus git commit identifier. For local installations, just put whatever info you need in version.txt file in lexonomy directory.

**Comment by iztokkosem** [comment]
All clear, closing issue again.
