### ISSUE TITLE
Automatically update beta installation from repository

### ISSUE THREAD

**Issue by iiegn** [elexis-eu/lexonomy#158]
The [beta installation](https://beta.lexonomy.eu) should be updated automatically from repository activity on the [beta branch](/elexis-eu/lexonomy/tree/beta/). 

Note: *automatically* does not necessarily mean *immediately* (depending on the activity on the branch and/or the installation, it might be frustrating to wait for a scheduled-for-later automatic update but also to test something and get kicked out because of an immediate-update.)

- [X] clearly mark the installation as `beta`
- [ ] add information about service interruptions and outages (e.g. due to updates)
- [ ] ?add information about **possible loss of all data** 

(Inspired by @mjakubicek news-on-Lexonomy-mail...)

**Comment by iiegn** [comment]
btw: i think, we should update-right-away after a commit/merge on the beta branch. A scheduling roster (e.g. once a day, at night) would seem to overly complicate the process...

**Comment by rambousek** [comment]
Current process - RPMs are built automatically from beta branch. Installation (update) is manual, to save us from broken installations.

**Comment by iiegn** [comment]
very nice! ...quick follow-up: is there a note about "the possible loss of all data?" - and if not: is it necessary to add one?

**Comment by rambousek** [comment]
sqlite databases are not touched during update, so no need for warning

**Comment by mjakubicek** [comment]
when is the update going to be automatic as well?
