### ISSUE TITLE
Change how costum entry editor works

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#167]
The current "costumized entry editor" system is simple, but since it is so simple, it is very hard for me to use things like images, user configs, using js libraries,

how it currently works:
- paste in javascript and css file, this is it.
- simmilarly for costumized view system

what I would like to do:

- an editor itself is a kind of a plugin
- plugin itself is a folder in plugins folder in website directory, must contain config.json
- config.json must have "javascript" files list, which are files, that are loaded in editor iframe
- - also style files list of CSS files, simmilar thing
- - one of the javascript files must define an interface (simmilar to how it is currently - harvest and editor)
- - this could also implement view function, so that I can unify view and edit code
- define lexonomy API, so that a plugin can access lexonomy functionality:
- - something was changed -> star in the change button
- - access to SKE
- - what else?
- config.json could be editable from user interface - this is how a user could constumize the editor 
- - this file could also include API keys and simmilar stuff, if javasript wants to access data from some other web api
- all the other files in the plugin can also be accessed (like images etc.)

Implementation:

- including js/css in documents should be an easy fix to edit.ejs
- accessing other files would be done via a new api, that also should not be a problem for me to write
- defining and implementing lexonomy API however is a bit out of my area of expertise
- - but I think writing a simple javascript file that implements what I currently need is something I can do
- config.json to be editable from user interface is a GUI thing and hopefully there I could get some assistence, but this is not a priority
- - choosing a plugin to use is also a gui stuff, but I know how to add this to the current system,
- implementing view this same way could also be skipped for now

Improvements:

- I can improve the speed of development for me substantially
- an editor is then available for multiple dictionaries without code duplication and with a simple upgrade path
- A plugin can easilly contain other javascript libraries without crazy hacks
- Having other data in plugin, like image, xslt and json files again adds more options
- Since I can have multiple javascript files, then I can use other languages, such as elm or typescript

Cons:

- more code
- not as simple of a system

**Comment by mjakubicek** [comment]
I think this needs to be split into smaller tasks so that it is manageable -- and simple :)

Some of the things that you are requesting are already possible, like showing the star that something has changed (you just call Screenful.Editor.changed()) or getting access to Sketch Engine. Also - what is it that is missing re images.

Having a stable API in Lexonomy for some general plugin mechanism is far from the current status of development, I think.

From my perspective the first and most useful thing would be to be able to have a library of custom editing widgets people could choose from (those would reside on server etc.), could perhaps share them etc.

For adding a configuration screen, see how I added e.g. the flags system, it is quite straightforward.

Finally, check the dictionary for the difference between custom and costume :-D

**Comment by gareins** [comment]
> I think this needs to be split into smaller tasks so that it is manageable -- and simple :)
> 

I agree, but to create smaller tasks it's good to know the end goal.

> Some of the things that you are requesting are already possible, like showing the star that something has changed (you just call Screenful.Editor.changed()) or getting access to Sketch Engine.  ... Having a stable API in Lexonomy for some general plugin mechanism is far from the current status of development, I think.

Yes, I already use Screenful.Editor.changed(). And I can easily accept that we are far from making an official API, but the problem is, that I have no idea how I would keep CJVT's _custom_ editors working if everything is subject to change anytime.

> Also - what is it that is missing re images.

Don't understand this one...

> From my perspective the first and most useful thing would be to be able to have a library of custom editing widgets people could choose from (those would reside on server etc.), could perhaps share them etc.

Would these be some sort of extensions for the xonomy editor or how would they work?

> For adding a configuration screen, see how I added e.g. the flags system, it is quite straightforward.

Ok, I see that is nicely in pull request #6 :)

> Finally, check the dictionary for the difference between custom and costume :-D

I'll try and keep the _pronaunciation_ correct :)

**Comment by gareins** [comment]
A friendly ping @mjakubicek

**Comment by gareins** [comment]
> Not quite in the frontend. These things haven't quite changed since Michal introduced them.

So it's probably not gonna change, but that is all the guarantee I can get - as long as we are clear.

> I meant: you can already use images in the custom editor.

You mean by hosting them on other servers or pasting in base64 values or how?

> Well, in the first place just the JS+CSS for custom editor as we have now, but shareable across users and dictionaries.

Ok, so this is just 1 thing of what I suggest (an editor is then available for multiple dictionaries without code duplication and with a simple upgrade path). 

I have a question: do you @ LC or do other users I don't know about use this feature often?

**Comment by mjakubicek** [comment]
> > Not quite in the frontend. These things haven't quite changed since Michal introduced them.
> 
> So it's probably not gonna change, but that is all the guarantee I can get - as long as we are clear.

Exactly.
 
> > I meant: you can already use images in the custom editor.
> 
> You mean by hosting them on other servers or pasting in base64 values or how?

Yes, that's how we do it.

> > Well, in the first place just the JS+CSS for custom editor as we have now, but shareable across users and dictionaries.
> 
> Ok, so this is just 1 thing of what I suggest (an editor is then available for multiple dictionaries without code duplication and with a simple upgrade path).
> 
> I have a question: do you @ LC or do other users I don't know about use this feature often?

Yes, we do use it quite extensively.

**Comment by gareins** [comment]
Ok, so if this is widely used and changing this would break existing code, then I just implemented it on top of the current system: https://gitea.cjvt.si/ozbolt/lexonomy-editor-plugin-system

This gives you a subset of the stuff I proposed in the proposal, only it is completely outside Lexonomy. What I am also planning to implement in the future is using the same code for "entry formatting" in Lexonomy, while editing config.json or the code is easy as it is hosted on a shared server at CJVT.

**Comment by mjakubicek** [comment]
Hm...I'm not sure whether we understand each other. Why wouldn't one want to have this inside Lexonomy? That is basically the idea of a library of editing widgets, to which one can add their own, isn't?

**Comment by iztokkosem** [comment]
Is this perhaps a suitable topic for this Wednesday's Lexonomy meeting?

**Comment by gareins** [comment]
> Hm...I'm not sure whether we understand each other. Why wouldn't one want to have this inside Lexonomy? That is basically the idea of a library of editing widgets, to which one can add their own, isn't?

Well, you said, that current custom editor javascript system works for you. I, however, like to do things differently. Stuff like using b64 to include pictures, having to manually import css/javascript libraries, including data inside javascript instead of using json files,... feels wrong to me somehow.

More importantly I can not use other languages, such as elm/coffescript etc. These languages usually create its own javascript file you are supposed to include, but can't do that with current system.

I felt with your responses, that the current system works and my points did not seem a concern to you, so I just decided to implement additional stuff on top without changing Lexonomy. And all can be good - at least that was the goal :)

**Comment by mjakubicek** [comment]
Eh - as you wish. You raised a large number of issues and I suggested to split into smaller tasks and address individually. The plugin management is e.g. independent of handling images (or how did you envisage that your solution would solve that?). In the end what you did seems to me very close to what I meant, that's all I'm saying -- just that I think it would be better integrated in Lexonomy without replacing the current mechanisms (they can live next to each other without issues).

**Comment by gareins** [comment]
Actually the images can be part of editor (lets say buttons) or they can be bound to dictionary, as is the case with some Twitter dictionary that I had done a bit of work a while ago. Bit it's not just images, other static files would need to be handled in a similar fashion (currently I have json and xslt files)

I think I'll go ahead and make a branch and will try to do this as part of Lexonomy, not changing the current system and then we can discuss that.

**Comment by mjakubicek** [comment]
The real issue with static files is not how to "edit" them but how/where to store them. So far when we discussed that we always find the best solution that each dictionary would have another .sqlite database for media (static) files, from which the backend would be pulling them. Bear in mind that doesn't require b64, just dynamic generation of the content.
