### ISSUE TITLE
beta:custom editor on new dictionaries fails

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#176]
## Reproduce

1. create new dictionary
2. configure it so that it uses empty custom editor
3. click edit

You get error on the backend.

### Error: 500 Internal Server Error

Sorry, the requested URL '$URL/vdjcfx43/edit/entry' caused an error:

Internal Server Error

### Exception:

`KeyError('xonomyMode',)`

### Traceback:

Traceback (most recent call last):
```
  File "$PATH/website/bottle.py", line 996, in _handle
    out = route.call(**args)
  File "$PATH/website/bottle.py", line 2007, in wrapper
    rv = callback(*a, **ka)
  File "lexonomy.py", line 63, in wrapper
    body = callback(*args, **kwargs)
  File "lexonomy.py", line 97, in wrapper_verifyLoginAndDictAccess
    return func(*args, **kwargs)
  File "lexonomy.py", line 720, in dicteditdoc
    return template("edit.tpl", **{"siteconfig": siteconfig, "user": user, "dictID": dictID, "dictTitle": configs["ident"]["title"], "flagging":configs["flagging"], "doctypes": doctypes, "doctype": doctype, "xonomyMode": configs["editing"]["xonomyMode"]})
KeyError: 'xonomyMode'
```

**Comment by gareins** [comment]
This happens because python's dictionary has different semantics than javascript's object. When accessing key in javascript object, it just returns undefined and this is why master does not fail. On the other hand, the Python just raises an exception. 

To match the two, take a look at commit 5d88b0bcab25a70b25f8946813a3581ecda7162c which fixes the behaviour, at leas as far as I can tell...

I am gonna assign this to @mjakubicek , since you wrote the function in 068c6c093e4926cfebd790f9fd06c4f65f52dfd0 and I am waiting for a review.

**Comment by rambousek** [comment]
Seems like good solution, I'm merging your commits to beta branch
