### ISSUE TITLE
beta: custom editor included by template escapes special HTML characters

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#177]
## Reproduce
Just use some custom editor with [any special HTML character](https://www.degraeve.com/reference/specialcharacters.php) , such as `"'<>`.

## Solution

Match old javascript template behaviour with new bottle templates. Example solution for just this particular case is in commit f3d2915f0fc397a7d6bfe4fdc273e5e9d3006b62.

**Comment by rambousek** [comment]
This is working. And _js is not used in other templates, so this problem is fixed.

**Comment by gareins** [comment]
Unfortunately javascript is not the only thing that needs to be properly escaped. Lets say when including _css in entryeditor.tpl, this does not work:

```css
  background-image: url("http://www.example.com/bck.png");
```

Fix is the same as before.  Also there is error with "." before _css in this same template.
