### ISSUE TITLE
Bad merge on master

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#184]
I should not be pushing on github at this hour, and I am very sorry. I wanted to merge a commit into beta, but merged it into master. It broke kind of everything.

I have managed to revert the #182 pull request in the branch reverting-master. It should be the same state as before the merge and should be mergable into master to fix the situation. But I will not be messing with master today anymore and hopefully when somebody reviews this tomorrow, the fix will be easy (merge in aforementioned branch).

Again, I am very sorry. I will be available on email tomorrow if anyone needs me.

**Comment by gareins** [comment]
How I reversed it is with these commands in reverse order:
```
git revert --no-commit 5d88b0b
git revert --no-commit f3d2915
git revert --no-commit c1b8873
git revert --no-commit b12caa1
git revert --no-commit 71bc55b
git revert --no-commit d074b17
git revert --no-commit cf36c32
git revert -m 1 --no-commit 9830707
git revert --no-commit 7b0d87d
git revert -m 2 --no-commit 8e001bb
git revert --no-commit 5d147cc 
```

**Comment by rambousek** [comment]
master branch seems to be working fine
