### ISSUE TITLE
manual linking

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#187]
1) link database
This would be just another standalone sqlite db within Lexonomy, with a single two-column table for the moment (once it gets too big, we may split it), with rows containing dictionary keys (see below) in the form of "DICTID:<key>" that are linked.
Then there needs to be some simple end point in Lexonomy to search and retrieve links for a particular key or whole dictionary, and to store a new link.

2) keys
Lexonomy needs to be aware of what may be linked in a dictionary, i.e. what may be a unique key. By default/mostly this would be entries and senses. In the configuration we need a widget where people setup which elements are linkable, and what is the key for them (using the string %sign notation that is used there already). Typically this would be:

<entry> -- key: "%(headword)-%(pos)"
<sense> -- key: "%(disambiguator)"

We probably should support adding an "order" attribute automatically as last resort identification (esp. for senses). But this should be in the data, so people click to get senses numbered, this would add an attribute into the XML and they could then use it to setup the keys.

3) interface
Elements that Lexonomy will know about that are linkable will show a button to link them, this would open a dialogue/dropdown where people choose the dictionary they want to link to (which they of course need to have access to; and this will be stored in cookies so they don't need to re-select until they want to change it) and then the headword (through an auto-complete).

**Comment by simonkrek** [comment]
So far: https://beta.lexonomy.cjvt.si/bmyp3urx/

**Comment by rambousek** [comment]
Backend API:
- links are stored in data/crossref.sqlite
- add link: _lexonomy_/_dictID_/links/add?source_id=_source entry_&target_dict=_target dict_&target_id=_target entry_
- user needs edit permission on source dictionary (dictID), source/target entry ID is not necessarily entry ID, but can also be definition etc (whatever frontend specify)
- response includes parameters, plus unique linkID
- get links going from dictionary: _lexonomy_/_dictID_/links/from
- user needs permission on dictID, shows all links with dictID as source dictionary; optional parameters source_id, target_dict, target_id
- get links going to dictionary: _lexonomy_/_dictID_/links/from
- user needs permission on dictID, shows all links with dictID as target dictionary; optional parameters source_id, source_dict, target_id
- delete link: _lexonomy_/_dictID_/links/delete/_linkID_
- user needs edit permission on source dictionary (dictID), must specify linkID

API is installed on beta.lexonomy.eu

**Comment by rambousek** [comment]
Changes to make:
#200 
#201 
#202 
#203 
#204

**Comment by rambousek** [comment]
New requests:
#226 
#227
