### ISSUE TITLE
headword wrapping for examples no longer works (reported by Ivana)

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#188]
The authors of the Croatian dictionary of Idioms used to be able to mark idioms or keywords (using <h>) in examples, but this feature is no longer available. Was it removed with the latest update?

**Comment by iztokkosem** [comment]
I think this must have been left out when moving to Python.

**Comment by rambousek** [comment]
This was caused by bad formatting in default dictionary template. Newly created dictionaries will have correct formatting.
To fix this in existing dictionaries, go to Configure-Entry formatting and choose style for **h**
