### ISSUE TITLE
Lexonomy.eu slower than local installations?

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#189]
I just happen to have the project "KSSS-2500-meniji" on Lexonomy.eu and our local installation, and I noticed that on .eu the entry loading works a bit slower, sometimes the difference is more noticeable. Is that due to server workload or something like that?
It is nothing major but I would still like to know why this occurs.

**Comment by rambousek** [comment]
Sometimes, server may have high workload, mainly data processing for other tasks. Usually, response should be fast. So if you notice some serious issue with lexonomy.eu speed, please contact support, and we will take care of it
