### ISSUE TITLE
show direct links to an entry for editing and viewing

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#193]
for editing, it is http://localhost/mydictionary/edit/entry/#123456

**Comment by mjakubicek** [comment]
and for viewing?

**Comment by rambousek** [comment]
edit: http://localhost/mydictionary/edit/entry/123456

view: http://localhost/mydictionary/edit/entry/view123456

public view already had links: http://localhost/mydictionary/123456
