### ISSUE TITLE
Entry publication XSL problem

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#194]
We have a problem with displaying entries using XSL. Basically, whatever you put in, nothing is displayed in the main Lexonomy window. This happened after we updated to the latest version.

Although we are dealing with this mainly on our local installation (and it is the same on ELEXIS Lexonomy installation), I have noticed this problem with one of my dictionaries in Lexonomy.eu. Which makes me wonder whether anyone else has spotted the problem?

**Comment by iztokkosem** [comment]
This seem to solve itself with reindexing, but there is one of our dictionaries in Lexonomy.eu (https://www.lexonomy.eu/zwkaq8ym4) that is an exception. As the list of entries is not loaded after reindexing, I suspect we are back to the old problem related to loading large entries (as is the case with this particular dictionaries). Miloš already fixed this problem once, so perhaps the correction was lost/overwritten when migrating to python?

**Comment by iztokkosem** [comment]
OK, now that dictionary works, although on opening it takes around 30 seconds for the list of entries to load up. Has anyone been working on this or is this a case of miraculous solution?

**Comment by rambousek** [comment]
we did some tweaks with entry list and XSL in November/December, so this was probably related. Let me know if you spot some problem again.
