### ISSUE TITLE
flag label inserted into the wrong part of the entry

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#196]
There is currently a problem in master where the flag label is inserted immediately after the entry tag, causing XML error and display issues in Lexonomy.

Miloš looked at this and says:
- the original regexp in JS was:

.replace(/(\=)\"([^\"]*)\"/g, "$1'$2'")

- the new one is:

xml = re.sub(r"(\=)\"([^\"]*)\"", "\1='\2'", xml)

notice the additional equal sign in the second argument, I guess that's a typo, or was it intentional Adam? On top of that, the second argument also needs to be double-escaped or r-string, so it should be:

xml = re.sub(r"(\=)\"([^\"]*)\"", r"\1'\2'", xml)

The regexp there is some quotes/apostrophes normalization I copied over from some other code in Lexonomy back then, I think, and it should be above all rewritten to be slightly more readable:

xml = re.sub(r"\=\"([^\"]*)\"", r"='\1'", xml)

**Comment by iztokkosem** [comment]
Adam replied: this seems like a typo. I vote for last regex, I'm not sure why we need = in parentheses, that was probably useful in other parts of Lexonomy, but not in this case.

We have tested this on our installation and it seems to work fine, so it can be implemented into master too.

**Comment by iztokkosem** [comment]
Adam wrote: this seems like a typo. I vote for last regex, I'm not sure why we need = in parentheses, that was probably useful in other parts of Lexonomy, but not in this case.

We have now tested this on our local installation and it seems to work fine so it can be implemented into master.

**Comment by iztokkosem** [comment]
Latest update: we have tested on our local installation and I noticed one weird thing - we have a tag for flags called <status> at this level:
<entry>
<head><status/></head>
<body></body>
</body>

So basically it is within the header info. When I select <status> as the flag tag and insert a tag, a new <status> tag is inserted immediately after the opening <entry> tag and before <head>. Is that expected behaviour?

**Comment by gareins** [comment]
Should be fixed on beta branch with commits e3c5151cfd42c770d1c41d8c128beac8e66e26e4 and be2e6cf.
