### ISSUE TITLE
Only 26 different registration tokens

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#197]
When a user registers he is sent a link with registration token. The token is generated in this line of code:

```py
token = hashlib.sha1(hashlib.sha1(random.choice(string.ascii_uppercase).encode("utf-8")).hexdigest().encode("utf-8")).hexdigest()
```

This line of code generates only 26 different values, check via:

```py
len(set([make_token() for _ in range(1000)]))
```

This means that anyone can register with any email he wants to and just need to try 26 different confirmation links. A simple alternative could be:

```py
token = "".join(random.choice(string.ascii_uppercase for _ in range(64))
```

**Comment by mjakubicek** [comment]
:roll_eyes: :see_no_evil:
the reset password function has the same problem, so if you know somebody has requested password reset, or if you can trick them into doing it, you could hijack the account.

I've just fixed that, thanks for spotting.

We should also depart from sha1 generally. It's no big deal now (the costs of breaking sha1 are still very high), but should be done rather sooner than later.
