### ISSUE TITLE
Entry size indicator

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#20]
Would be nice for each headword (in the headword list on the left-hand side) to a visual indicator of its size.

**Comment by TejaGo** [comment]
Adam Rambousek 27 Jul, 2018
What is "size"? Number of characters, elements, senses...?


iztok.kosem@ijs.si 26 Oct, 2018
Good point. Senses could potentially be useful but character count might be more telling.

**Comment by mjakubicek** [comment]
Not needed.
