### ISSUE TITLE
searching lower/upper case with non-English letters

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#219]
When searching in Lexonomy using non-English letters as the beginning ones (e.g. č, š, ž), the search is case sensitive (e.g. you get different results for č or Č), whereas for other letters it is case insensitive (a gets the same hits as A). This should be unified.

**Comment by rambousek** [comment]
I made search case insensitive for all unicode characters (dictionary must be reindexed before use)
