### ISSUE TITLE
Error when installing Lexonomy on Linux Ubuntu 18.04 LTS (Bionic)

### ISSUE THREAD

**Issue by leobardooscar** [elexis-eu/lexonomy#241]
**Describe the bug:**
Installing Lexonomy locally on Ubuntu 18.04 (Bionic) fails for these reasons:
```
 File "lexonomy.py", line 6, in <module>
    import ops
  File "/var/www/html/lexonomy-master/website/ops.py", line 19, in <module>
    from icu import Locale, Collator
ImportError: cannot import name 'Locale'
```

**To Reproduce**
1. Go to '/lexonomy-master/website/.'
2. After installing all requirements 'pip install -r requirements.txt'
3. Run app 'python3 lexonomy.py'
4. Error appears:
```
File "lexonomy.py", line 6, in <module>
    import ops
  File "/var/www/html/lexonomy-master/website/ops.py", line 19, in <module>
    from icu import Locale, Collator
ImportError: cannot import name 'Locale'
```
5. If line 19 in ops.py file is commented "from icu import Locale, Collator", Lexonomy runs and opens Login page, but obviously you are not able to create any dictionary.

**Environment (please complete the following information):**
 - Linux Ubuntu 18.04.5 LTS (Bionic) 
 - Browser: Firefox 84.0 (64-bit) 
 
Thanks for your help! :-)

**Comment by rambousek** [comment]
You need to install PyICU library. It should be installed by requirements.txt, but try to install it manually.
