### ISSUE TITLE
Text with markup, menu doesn't appear

### ISSUE THREAD

**Issue by yevvie** [elexis-eu/lexonomy#244]
**Describe the bug**
Child element of "Text with markup" option does not appear to be picked from child list in the edit mode.

**To Reproduce**
1. Go to 'Configure/Structure'.
2. Create an element, set it to 'Text with markup'.
3. Create a child of that element.
4. Save settings.
5. Enter edit mode.
6. Add new entry.
7. Click parent element to add child - menu does not display child elements.

**Expected behavior**
A child element category should be visible to add child elements with a click.

**Screenshots**
![2021-05-20 12 28 37 www lexonomy eu 6ef299be969b](https://user-images.githubusercontent.com/36525679/118964278-a242f800-b967-11eb-8628-071781d9e560.png)
![2021-05-20 12 29 53 www lexonomy eu 6fb9c59dddaf](https://user-images.githubusercontent.com/36525679/118964280-a2db8e80-b967-11eb-9e4c-aefbdf7aaf8b.png)
![2021-05-20 12 30 02 www lexonomy eu 9a724936ca81](https://user-images.githubusercontent.com/36525679/118964282-a2db8e80-b967-11eb-8248-ee0a99a91f34.png)

**Environment:**
- Windows 10 (Build 19042.985)
- Vivaldi Browser 3.8.2259.42 (Stable channel) (64-bit)

**Additional context**
- Using browser version only

**Comment by rambousek** [comment]
This issues is now fixed. Behaviour is a bit different - enter text in "definition" element, each word is displayed with gray background, Ctrl+click the word you want to highlight and select "wrap"
