### ISSUE TITLE
Subentry sharing doesn't work

### ISSUE THREAD

**Issue by eftomi** [elexis-eu/lexonomy#267]
**Describe the bug**
When adding shared subentry, the search facility doesn't return any candidates

**To Reproduce**
1. In dictionary structure (**Entry settings > Structure**), create a child element of type text
2. Under **Expert settings > Subentries** add this child element to the list of subentires
3. Under **Edit**, create a new entry together with child element
4. Ender **Edit**, create a new entry and try to search for the child element created in previous step
5. There are no results, developer's console reports `GET https://www.lexonomy.eu/a49ax7ir/subget/?lemma=banana&doctype=subentry 500 (Internal Server Error)`

**Expected behavior**
I suppose the user should get a list of subentries from other entries which meet the search criteria-

**Screenshots**
Animated GIF
![subentries](https://user-images.githubusercontent.com/15959669/155684083-2cbfb3c6-8cf5-40a4-88fa-7a76ce1df372.gif)

**Environment (please complete the following information):**
 - Windows 10
 - Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Additional context**
I cannot find any documents that describe this functionality, I might misunderstand the concept.

**Comment by rambousek** [comment]
Thank you for report, this is now fixed
