### ISSUE TITLE
Text near illegible since last big update (font color/background color)

### ISSUE THREAD

**Issue by queerterpreter** [elexis-eu/lexonomy#275]
**Describe the bug**
I see Lexonomy's had a facelift since I last consulted my glossaries, which is generally great! However, I now can't read any text that's in any color outside of black. All of them have a background in that same color (albeit lighter) which makes them really challenging. 

**To Reproduce**
This happens everywhere at all times, both when consulting the dictionary itself and in formatting view.

**Expected behavior**
If there's no background color selected, the background should stay transparent. Otherwise, there should be an option for "transparent" or "white" background color in the drop-down, which is absent.

**Screenshots**
[Dictionary view](https://imgur.com/a/wHlsPoI)
[Formatting view](https://imgur.com/sDvq138). You can see here that I have a font color selected, but no background.
[Formatting view 2](https://imgur.com/7u85Akn). Same settings, but I tried using the background colors. They don't overrule the wonky background, but instead add sort of an outline. Look specifically at the word in red, the headword.

**Environment (please complete the following information):**
 - OS/Device: Windows 10, iOS 15.4.1
 - Browser & Version: Windows: Firefox 99.0.1 + Chrome 100.0.4896.127, iPhone: Safari

**Additional context**
None

**Comment by svoboda-ske** [comment]
Thank you for reporting the bug. It will be fixed soon, hopefully today:)
