### ISSUE TITLE
Local build - New dict template doesn't render the "id" attribute for the url input

### ISSUE THREAD

**Issue by namoshizun** [elexis-eu/lexonomy#279]
**To Reproduce**
1. Make a local build following the instructions [here](https://github.com/elexis-eu/lexonomy/blob/main/INSTALL.md)
2. Go to http://localhost:8080/#/make
3. Fill in all required fields
4. Click "Create Dictionary"

**Describe the bug**
Received an error prompt saying the URL is already taken. Further diving into the source code, I found out that's because I've already created a dictionary with an empty ID, and the current creation will cause an ID clash because the new dict's ID is also empty... 

From the form element, it appears that the URL input tag doesn't have the "id" attr, leading to every dict creation payload misses the "url" information.

**Screenshots**
**[1]**
<img width="1166" alt="Screen Shot 2022-05-15 at 12 07 48 pm" src="https://user-images.githubusercontent.com/14081899/168457007-ad46e04a-96b8-4e04-99bc-1cfc15057806.png">

**[2]**
<img width="1172" alt="Screen Shot 2022-05-15 at 12 07 22 pm" src="https://user-images.githubusercontent.com/14081899/168457008-3abaf980-8d1a-47e6-8b68-fbc7132499b9.png">

**Expected behavior**
A new dictionary is created 

**Environment (please complete the following information):**
 - OS/Device: MacOS
 - Browser & Version: Chrome 101

**Comment by svoboda-ske** [comment]
Thank you for your detailed report, it is fixed now.
