### ISSUE TITLE
Stop reloading entry list after every save

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#29]
Lexonomy reloads the entry list (on the left hand side of the screen) each time an entry is saved. This is in case the title of the entry has changed as a result of the save and the entry now needs to appear somewhere else in the alphabetical order. It turns that this was not a good idea, for two reasons:

- When the entry list is very long it takes very long to reload it and the user can erroneously assume that the entry has not been saved yet.

- When the entry has in fact changed and the entry moves somewhere else in the alphabetical list (which may be off-screen) it turns out that users find it confusing.

**Comment by michmech** [comment]
Thse changes have already been implemented in Screenful, and will appear in Lexonomy automatically once Screenful is unforked (#84).

**Comment by iztokkosem** [comment]
This has been fixed, yes?
