### ISSUE TITLE
with custom xsl, entries do not show formatting in viewer, but do in editor

### ISSUE THREAD

**Issue by fiddler44** [elexis-eu/lexonomy#292]
**Describe the bug**
Our dictionary uses a custom xsl and the formatting displays correctly in the editor, but only shows unformatted text in the viewer. This was not an issue until a couple months ago. The links are to a cloned version of the dictionary in which this issue was first encountered.

**To Reproduce**
1. Go to [edit in this dictionary](https://www.lexonomy.eu/#/a77xrbpt/edit). 2. 
2. View any entry. 
3. Go to [view in this dictionary](https://www.lexonomy.eu/#/a77xrbpt).
4. See that no entry displays the formatting seen in the edit section. 

**Expected behavior**
We expect the entries to display in the viewer the same way they do in the editor. 

**Screenshots**
"Edit" Viewer: 
<img width="1293" alt="Screen Shot 2022-07-03 at 9 27 33 PM" src="https://user-images.githubusercontent.com/40439370/177066256-c0dd94de-a5f2-4592-a21a-1131fc3c24b4.png">

"View" Viewer:
<img width="1301" alt="Screen Shot 2022-07-03 at 9 29 12 PM" src="https://user-images.githubusercontent.com/40439370/177066357-918f772c-6aac-4ad6-a31a-0da301f868e3.png">

**Environment (please complete the following information):**
 - Encountered on Mac and iOS
 - Using Chrome Version 100.0.4896.75 and Safari 15.5

**Additional context**
This displayed correctly until a couple months ago, but broke during an update to Lexonomy. Unfourtunately I do not know exactly when this happened.

**Comment by iztokkosem** [comment]
I would perhaps recommend moving your dictionary to lexonomy.elex.is (where an older stable version is running), as we are currently working on significantly updates.

**Comment by rambousek** [comment]
Thank you for reporting, display is now fixed
