### ISSUE TITLE
Cross-references

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#34]
Users will be able to include cross-references from one entry to another entry or to a location in another entry (such as specific sense inside a dictionary entry). Lexonomy will make sure the cross-references are clickable when the entry is formatted for display. Also, Lexonomy will keep track of what cross-references what, will make sure that cross-references are never broken, and (if the dictionary is so configured) will make sure that cross-references are reciprocated: if X cross-references Y, then Y must also cross-reference X.

**Comment by michmech** [comment]
I want to do this myself.
