### ISSUE TITLE
Richer formatting options

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#36]
The entry formatting (visualization) options in the current version of Lexonomy are kind of OK (they're certainly better than in the beta version) but they need more sophistication. We need two things:

- On the one hand, we need more and richer formatting options, similar to what you'd find in a WYSIWYG word processor.

- On the other hand, we need a "quick settings" option where people could choose from a pre-defined template, for example Make this XML element look like a sense or Make this XML element look like a headword.

iztok.kosem@ijs.si 18 Sep, 2018
I would say that anything to enable quicker and more user-friendly editing would be most welcome. As soon as the dictionary structure is more complex/rich and contains many items, opening different tags and entering text becomes very tedious and time-consuming.

Michal Boleslav Měchura 18 Sep, 2018
Iztok, what you're saying is true but not relevant to this task. This task is about the options Lexonomy has for the pretty-printed formatted visualizations of entries. This task is not about the XML editor.

iztok.kosem@ijs.si 18 Sep, 2018
OK, where do I move my comment then? Or even better, if you know a place, feel free to copy it there.

**Comment by michmech** [comment]
Probably not needed any more, given that people can upload a custom XSL/CSS stylesheet now.

**Comment by iztokkosem** [comment]
The last comment is true, this can be closed now.
