### ISSUE TITLE
Autosave in some configs

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#42]
Every screen in the configuration section (as well as the One-Click Dictionary API key screen) requires you to click the Save button but save your changes. In some cases this is unintuitive and people keep forgetting it.

**Comment by michmech** [comment]
Done in the [One-Click dictionary settings](https://www.lexonomy.eu/oneclick/) screen.

Not done anywhere else. All the other configuration screens are quite complex and I find it more logical to expect the user to let the user decide for themselves when they are ready to save their changes.
