### ISSUE TITLE
Alphabetical sorting

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#45]
Lexonomy needs more sophistication in the alphabetical sorting of entries. The current approach in which the lexicographers can input their own alphabetical sequence, is good and very flexible but works only for languages with alphabetical (and perhaps syllabic) scripts. We need:

- A good solution for ideographic scripts like Chinese (this is an issue for user lingoriol@yahoo.es who is working in Lexonomy on Chinese). Probably we need to let the user select a collation and simply outsource the problem to a library. This would be good for all languages, but the current "manual alphabet" must continue to be available too, as an optional override, to make sure Lexonomy continues having good support for minority languages with no standardized collations, for non-standard alphabetical sequences and so on.

- Support for explicit sorting keys encoded in the entries: this implies sorting entries by something else than the headword.

-------

Milos Jakubicek 25 Jul, 2018
 ­
Pavel Rychlý on Wednesday Nov 29, 2017 10:45 AM:
why not to use standard locales:
var a = ['hlad', 'chleba','řeka', 'rok']
a.sort(function (x,y){return x.localeCompare(y,'en');})
\>>  ["chleba", "hlad", "řeka", "rok"]
a.sort(function (x,y){return x.localeCompare(y,'cs');})
\>>  ["hlad", "chleba", "rok", "řeka"]

---------------------- ­
Michal Boleslav Měchura on Wednesday Nov 29, 2017 10:49 AM:
That's more or less what I have in mind with the "let the user select a collation" option.
AR
Adam Rambousek 26 Jul, 2018
note: nodejs needs to install full locale support https://www.npmjs.com/package/full-icu

**Comment by michmech** [comment]
> Support for explicit sorting keys encoded in the entries: this implies sorting entries by something else than the headword.

This is done already.

What remains missing is a feature for selecting and applying a collation.
