### ISSUE TITLE
Upload your own schema

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#50]
Dictionary administrators who do not want to use Lexonomy's schema editor will be able to upload a schema they have written in some other formalism, such as a Xonomy document specification http://www.lexiconista.comm/xonomy/ or a DTD.

**Comment by michmech** [comment]
Done (mostly by @rambousek) for DTDs and for Xonomy document specifications. Two questions to discuss:

(1) Do users need any other schema formalisms? XML Schema, ...

(2) Also, we talked about inducing a schema from existing entries. I believe @rambousek was working on that but 'Im not sure what the status is.

The answer to (1) is probably "no" if we're going to have (2).

**Comment by rambousek** [comment]
Schema detection is done (more or less... will probably break on very complex structures) in #52 

All we need now is GUI integration
