### ISSUE TITLE
Rich-text formatting in blurb

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#57]
When publishing a dictionary in Lexonomy, the current version allows you to supply a 'blurb': a short description which appears on the dictionary's homepage. The blurb is in plain text.

Lexonomy will allow rich-text formatting in the blurb: bold, italics, paragraph breaks, clickable links, etc. (in other words: Markdown).

**Comment by michmech** [comment]
Done. People can us Markdown in the blurb.
