### ISSUE TITLE
Make the push/pull APIs public

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#63]
So other people can build other things to push/pull from.

Suggested by IVDTN who would like to pull example sentences from their own database of citations (not a corpus).

**Comment by michmech** [comment]
I guess it's too early to be making any APIs public yet.

Related to #53 API for integrating Lexonomy into customer's internal workflow.

**Comment by mjakubicek** [comment]
I think it should be emphasized that Lexonomy already has a public API in the sense that it is a web application where more or less any action can also be performed by a remote script.
To give an example, this is how one can remotely download a dictionary:

```
curl -c cookie.txt 'https://www.lexonomy.eu/login.json' --data 'email=<EMAIL>' --data 'password=<PASSWORD>'
curl -b cookie.txt 'https://www.lexonomy.eu/<DICTIONARY_ID>/download.xml'  > output.xml
```

For some particular actions things might be done easier than now, but we need to know what exactly that should be. I assume for IVDNT wants is already possible. @jan-niestadt
