### ISSUE TITLE
Problem with Entry formatting feature when using DTD

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#74]
When uploading a project using own schema (DTD), the projects hangs when trying to prepare Entry formatting. It keeps showing "Getting list". A temporary workaround is changing Entry formatting into CSS/XSL option first and writing something there, then adding DTD, and then uploading entries. Then you can continue modifying the settings.

**Comment by michmech** [comment]
Fixed (see commit ff32d7d5283f86bf57379369140c091afe120a59) by baby-proofing the schema designer and the template designer against long and/or invalid schemas.

**Comment by iztokkosem** [comment]
It is still happening, as I reported.

**Comment by michmech** [comment]
Fixed for real this time by commit 751b7e1d89b7463d6b46843147998ac9c6fdcc23.

**Comment by iztokkosem** [comment]
Ožbolt, can you implement this on lexonomy.elex.is so I can test it?

**Comment by iztokkosem** [comment]
This has been resolved.
