### ISSUE TITLE
SkE dropdown menu should be available for each inflected form listed within an entry (search by word /ideally: word_lemmacase/)

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#83]
we need some good solution of how to specify things within an entry that this should apply for

**Comment by michmech** [comment]
The more general problem here is that Lexonomy doesn't know the meanings of the XML elements and attributes.

- Optionally, Lexonomy knows where the headword is. This is configured under Configure > Entry settings > Headwords.

- Optionally, Lexonomy knows where the examples, collocations, thesaurus items and definitions are. This is configured under Configure > External data sources.

These two settings are scattered and ad-hoc. It would be a cool innovation to unify this into a single scheme for describing the lexicographic semantics of the XML schema in each dictionary. Then, based on that, Lexonomy could offer dropdown menus etc. in the XML editor, as well as other cool things like export into/import from TEI-Lex0.

**Comment by mjakubicek** [comment]
implemented in c062e7bfaa4a77dea7fcbdd6b372f8e138de2a47
