### ISSUE TITLE
Unfork Screenful

### ISSUE THREAD

**Issue by michmech** [elexis-eu/lexonomy#84]
**Background:** Everything in the `/website/libs/` directory are copies of external libraries and should never be edited here. If we need to change an external library we should send a pull request to the external library, wait for it to be accepted, then update its copy here.

**The issue:** Unfortunately, our copy of the [Screenful](https://github.com/michmech/screenful) library has been edited a lot lately to support Lexonomy-specific features such as entry flagging, line numbering and reverse entry sorting. This has caused a fork from the original Screenful library.

**The fix:** I am going to unfork the fork by re-implementing all the Lexonomy-specific features in the original Screenful library and bring our copy back in sync.

**Lesson to learn from all this:** Never edit anything in the `/website/libs/` directory.

**Comment by mjakubicek** [comment]
I'm not sure whether this is feasible. Most of Lexonomy's frontend relies on Screenful so any changes there inevitably mean changes to Screenful too (I've now done some more again, sorry). Many of the changes might not be appropriate for the original Screenful and I don't think that's wrong: libraries of this type are never "one size fits all" and once they reach a certain development stage, it's usually better to fork them then to try integrate all what is needed for Lexonomy into some kind of universal thing that will not be used anywhere else.

**Comment by mjakubicek** [comment]
Moreover, if you really want to do this, please accompany Screenful code with a licence. From this point of view this introduces additional complexity too.

**Comment by michmech** [comment]
Sorry, I had forgotten that Screenful didn't have a licence. [It does now.](https://github.com/michmech/screenful/blob/master/LICENSE)

**Comment by michmech** [comment]
I still want to do this. I see nothing in the changes made to Lexonomy's fork of Screenful that are so Lexonomy-specific that they shouldn't be in Screenful.

**Comment by mjakubicek** [comment]
Ok, if you think so. But you cannot expect that anybody will in the future first try to get changes upstream and then use them in Lexonomy. It will always be vice versa.

**Comment by michmech** [comment]
I don't expect that (anymore) and I'm OK with that.
