### ISSUE TITLE
separate process for blocking tasks

### ISSUE THREAD

**Issue by rambousek** [elexis-eu/lexonomy#85]
use separate process for blocking tasks (eg. import, database reindexing).

https://itnext.io/multi-threading-and-multi-process-in-node-js-ffa5bb5cde98
https://blog.logrocket.com/node-js-multithreading-what-are-worker-threads-and-why-do-they-matter-48ab102f8b10

**Comment by mjakubicek** [comment]
from abf43cb64d2f21b20f92c8840adda4d777806288 on this is the case for import, though there should be a more user-friendly handling of any blocking task in terms of whether the dictionary is usable meanwhile, what to show to users etc.
