### ISSUE TITLE
RDF endpoint?

### ISSUE THREAD

**Issue by eroux** [elexis-eu/lexonomy#87]
might be connected to https://github.com/elexis-eu/lexonomy/issues/61

I'm wondering if it would be possible to automate an RDF export of the headwords, definitions, etc. using the [Ontolex](https://www.w3.org/2016/05/ontolex/) vocabulary? I think it could have two aspects:

- a global RDF export of a dictionary
- an RDF export of each entry accessible at the entry URL when requested with either a special URL (adding `.ttl` at the end for instance) or using the headers (the [Cool URI](https://www.w3.org/TR/cooluris/) principles)

What do you think?

**Comment by michmech** [comment]
This is currently not doable because Lexonomy doesn't actually "know" where the headwords, definitions etc. are. All Lexonomy "sees" inside the entries is XML elements.

(By the way, this feature request is not related to #61. #61 is about an API in Sketch Engine, which is something else entirely.)

**Comment by rambousek** [comment]
Ontolex RDF export is supported to a certain extent - Lexonomy is inducing headwords and senses based on well-known schemas and TEI-Lex0
