### ISSUE TITLE
cannot change dictionary name

### ISSUE THREAD

**Issue by iztokkosem** [elexis-eu/lexonomy#89]
Once the dictionary is created, you cannot change its name. The interface allows you to do it, and seems to save it too, however when you go back to the landing page, the old name is used again.

**Comment by michmech** [comment]
I am unable to reproduce this bug.

I am not sure if by dictionary name you mean its user-friend name or its URL. But I have just tried changing both (on a text dictionary I created) and it worked fine.

Is this happening only on one particular dictionary, perhaps? And if so, which one?

**Comment by iztokkosem** [comment]
Strangely, I also cannot reproduce the problem. I was replacing an old dictionary, and added a "-old" ending to the previous version. However, when it didn't work, I simply deleted it (saving all the settings etc. first). So it seems the issue was limited to that dictionary.
