### ISSUE TITLE
go2entry

### ISSUE THREAD

**Issue by gareins** [elexis-eu/lexonomy#92]
Trying to migrate a dictionary from an old installation, I came upon a go2entry global javascript function that does not work anymore. Is there a replacement?

**Comment by gareins** [comment]
It was apparently implemented in local js files, closing.

**Comment by gareins** [comment]
So, it turns out, I have no idea how to make this work. The implementation used to be this:

`function go2entry(title) {
  window.location =  "../?txt="+encodeURIComponent(title);
}`

But that triggers a 

> Blocked loading mixed active content "http://lexonomy.cjvt.si/furniture/public.css"

I saw, that screenful makes an api request to "../../../:dictID/entryread.json" with correct entry id. This request renders the xml using xslt on the backend and then just inserts the resulting html via $.html() inside the iframe. Should I just try and replicate this behaviour inside entry editor javascript?

**Comment by michmech** [comment]
The `go2entry()` function existed in an old beta version of Lexonomy. It took a string and caused Lexonomy to navigate to the first entry it could find that had that string as a headword.

In this version of Lexonomy you can create similar behaviour by making your XSL output this kind of HTML:

```html
<a class="xref" href="#" data-text="blabla">blabla</a>
```

Any `<a>` elements in the HTML output of your XSL, which have the `xref` class, will be converted into clickable links which, when the user clicks them, will cause Lexonomy to do a search for the string in the `data-text` attribute.

**Comment by gareins** [comment]
Thanks, that worked.
