### ISSUE TITLE
Local installation asks for consent to Lexical Computing terms of use

### ISSUE THREAD

**Issue by michmech** [elexis-eu/lexonomy#94]
When someone downloads Lexonomy's source code and sets up a local installation, the installation asks newly registered users to agree to Lexical Computing's tems of use:

> Terms of Use
> 
> Lexonomy is a service provided by Lexical Computing CZ s.r.o.. This service is provided free of charge for non-commercial purposes only. Lexonomy is still in the development phase and no warranties are given as for service availability or fitness for particular purpose.
> 
> Commercial users as well as users interested in a guaranteed service level need to contact us in order to obtain a subscription.
> 
> [ ] My usage is non-commercial and I agree to the terms of use

This is inappropriate on an installation not hosted by Lexical Computing. My suggestion is to make this configurable in `siteconfig.json` (and `siteconfig.json.template`), with three settable options:

(1) whether or not new users of this installation should be asked to agree to terms of use
(2) and if yes, what the wording is of the terms of use
(3) and what the wording of the "I agree" sentence is.

Alternatively, we only need options (1) and (2) if the "I agree" sentence is hard-coded and something general, such as "I agree to the terms of use". And if we have only the two options, then we can conflate them into one, a string which if empty implies "do not ask for consent".

**Comment by mjakubicek** [comment]
Sure -- and default settings should be "empty" so as not to ask for anything.

**Comment by rambousek** [comment]
new option in siteconfig.js

  "consent": {"terms": null, "confirm": null},

consent.terms - terms of use text
consent.confirm - confirm checkbox text
