### ISSUE TITLE
support for editing on mobile devices

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#95]

**Comment by iztokkosem** [comment]
Comment needs to be added somewhere that mobile editing does not work (perhaps the info on minimum screen width needs to be added too).

**Comment by mjakubicek** [comment]
when working on this, fonts should be loaded dynamically as needed to save bandwidth (over 50MB).

**Comment by rambousek** [comment]
New beta GUI editor will be responsive.
