### ISSUE TITLE
do not suppress SQL errors

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#96]
Now almost any db query has no error handling, this makes it difficult to debug when something goes wrong. The fix is easy:

```
      db.run(sql, params, function(err){
        if (err)
          throw new Error(err);
```

A good task for anybody who wants to help.

**Comment by jan-niestadt** [comment]
Maybe this needs to be done for other operations as well, e.g. fs.readFile

**Comment by jan-niestadt** [comment]
Question 1: if db.run doesn't pass a callback, or if the callback has no arguments, should I still apply this fix? I would think so (e.g. adding the argument and/or the callback), but don't want to break anything.

Question 2: does this fix need to be applied in the adminscripts as well? These seem to sometimes handle err by logging to the console, but not always. Maybe I should skip these scripts for now and focus on ops.js/lexonomy.js?

**Comment by gareins** [comment]
> Question 1: if db.run doesn't pass a callback, or if the callback has no arguments, should I still apply this fix? I would think so (e.g. adding the argument and/or the callback), but don't want to break anything.

Where this happens? There should be `db.close()` at least in callback...

I also wanted to write here a quick suggestion on how we could do this without hundreds of C-style error checks, that clutter the code

```
if(err) {
  // handle
}
```

There are two things here, first is that in express.js you are supposed to handle errors using (error middleware)[http://expressjs.com/en/guide/using-middleware.html#middleware.error-handling] (sorry, again middleware...). So you only have to raise an error.

And we come to the second thing, which would be to wrap database in its own module. And for every `db.run` or `db.get`, the module would insert a check after and raise the error. I will write a quick mockup tommorow and everyone will be able to comment on it.

**Comment by jan-niestadt** [comment]
Hmm, so the initial suggestion may not be the ideal fix then? I will need to learn more about Express if I am to continue with this. Also will be interested to see your mockup.

(btw I edited your comment to fix the link)

**Comment by gareins** [comment]
```js
Database = function(name, flags, callback) {
  this._db = new sqlite3.Database(name, flags, this.handle_error(callback));
  this._message = null;
  this._track = siteconfig.trackSql;
}

Database.prototype.report = function(message) {
  this._message = message;
  if(this._track) {
    console.log(this._message);
  }
}

Database.prototype.handle_error = function(callback) {
  return function(db) {
    if(db.err) {
      throw new Error(this._message); // maybe we need `self` here?
    }
    callback(db);
  }
}

Database.prototype.run = function(statement, parameters, callback) {
  this.report(`SQL run ${ args }`);
  return this._db.run(statement, parameters, this.handle_error(callback));
}

// other functions like close, all,...
```

With this we get tracking of sql statements and error handling with ?nice? messages. Only thing that we need to change in ops is `sqlite3.Database(` now becomes `whatever.Database(` and we remove all of the error handling.

**Comment by iiegn** [comment]
> Question 2: does this fix need to be applied in the adminscripts as well? These seem to sometimes handle err by logging to the console, but not always. Maybe I should skip these scripts for now and focus on ops.js/lexonomy.js?

i know too little about logging in node.js - that said: errors should never pass silently - unless explicitly silenced ;)
so, this makes one more issue: 
- handle errors *also* in `adminscripts`

**Comment by jan-niestadt** [comment]
If we take the approach suggested by @gareins (which I think we should) all errors (in both the application and adminscripts) are handled automatically (at least if you use the wrapped db object). 

Any existing error handling might have to be updated, e.g. by catching the Error thrown by the db function instead of checking the err value.

**Comment by gareins** [comment]
To comment on the pull request #124.

First, pros:

* error handling outside ops.js
* errors will report with message about the SQL statement that failed
* actually checks if sqlite file is a proper database (currently the check does not work) - this can be fixed by itself

cons:

* you need to pass the next function in order for express to catch the error

This is not so clear, so what do you think?

**Comment by mjakubicek** [comment]
no longer relevant since we switched to Python
