### ISSUE TITLE
allow reordering of dictionary list

### ISSUE THREAD

**Issue by mjakubicek** [elexis-eu/lexonomy#98]
For the case of having a lot of dictionaries on the front screen, it would be good to be able to reorder the list. Possible, mutually non-exclusive, options, entail:
- being able to arbitrarily reorder the list
- being able to mark a dictionary as favourite which would bring it to the top
- being able to archive the dictionary would would bring it to the bottom or to a separate view

This includes the problem of unwanted shares.

**Comment by rambousek** [comment]
duplicate of several issues #212 #213 #215
